
package cis.bir.publ._2014._07;

import org.tempuri.IUslugaBIRzewnPubl;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.*;
import javax.xml.namespace.QName;
import javax.xml.ws.*;
import java.net.MalformedURLException;
import java.net.URL;


/**
 * <p>Java class for anonymous complex type.
 *
 * <p>The following schema fragment specifies the expected         content contained within this class.
 *
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="pKluczUzytkownika" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 *
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
        "pKluczUzytkownika"
})
@XmlRootElement(name = "Zaloguj")
public class Zaloguj {

    @XmlElementRef(name = "pKluczUzytkownika", namespace = "http://CIS/BIR/PUBL/2014/07", type = JAXBElement.class, required = false)
    protected JAXBElement<String> pKluczUzytkownika;

    /**
     * Gets the value of the pKluczUzytkownika property.
     *
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *
     */
    public JAXBElement<String> getPKluczUzytkownika() {
        return pKluczUzytkownika;
    }

    /**
     * Sets the value of the pKluczUzytkownika property.
     *
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *
     */
    public void setPKluczUzytkownika(JAXBElement<String> value) {
        this.pKluczUzytkownika = value;
    }

    /**
     * This class was generated by the JAX-WS RI.
     * JAX-WS RI 2.3.1-SNAPSHOT
     * Generated source version: 2.2
     *
     */
    @WebServiceClient(name = "UslugaBIRzewnPubl", targetNamespace = "http://tempuri.org/", wsdlLocation = "https://wyszukiwarkaregontest.stat.gov.pl/wsBIR/wsdl/UslugaBIRzewnPubl.xsd")
    public static class UslugaBIRzewnPubl
            extends Service
    {

        private final static URL USLUGABIRZEWNPUBL_WSDL_LOCATION;
        private final static WebServiceException USLUGABIRZEWNPUBL_EXCEPTION;
        private final static QName USLUGABIRZEWNPUBL_QNAME = new QName("http://tempuri.org/", "UslugaBIRzewnPubl");

        static {
            URL url = null;
            WebServiceException e = null;
            try {
                url = new URL("https://wyszukiwarkaregontest.stat.gov.pl/wsBIR/wsdl/UslugaBIRzewnPubl.xsd");
            } catch (MalformedURLException ex) {
                e = new WebServiceException(ex);
            }
            USLUGABIRZEWNPUBL_WSDL_LOCATION = url;
            USLUGABIRZEWNPUBL_EXCEPTION = e;
        }

        public UslugaBIRzewnPubl() {
            super(__getWsdlLocation(), USLUGABIRZEWNPUBL_QNAME);
        }

        public UslugaBIRzewnPubl(WebServiceFeature... features) {
            super(__getWsdlLocation(), USLUGABIRZEWNPUBL_QNAME, features);
        }

        public UslugaBIRzewnPubl(URL wsdlLocation) {
            super(wsdlLocation, USLUGABIRZEWNPUBL_QNAME);
        }

        public UslugaBIRzewnPubl(URL wsdlLocation, WebServiceFeature... features) {
            super(wsdlLocation, USLUGABIRZEWNPUBL_QNAME, features);
        }

        public UslugaBIRzewnPubl(URL wsdlLocation, QName serviceName) {
            super(wsdlLocation, serviceName);
        }

        public UslugaBIRzewnPubl(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
            super(wsdlLocation, serviceName, features);
        }

        /**
         *
         * @return
         *     returns IUslugaBIRzewnPubl
         */
        @WebEndpoint(name = "e3")
        public IUslugaBIRzewnPubl getE3() {
            return super.getPort(new QName("http://tempuri.org/", "e3"), IUslugaBIRzewnPubl.class);
        }

        /**
         *
         * @param features
         *     A list of {@link WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
         * @return
         *     returns IUslugaBIRzewnPubl
         */
        @WebEndpoint(name = "e3")
        public IUslugaBIRzewnPubl getE3(WebServiceFeature... features) {
            return super.getPort(new QName("http://tempuri.org/", "e3"), IUslugaBIRzewnPubl.class, features);
        }

        private static URL __getWsdlLocation() {
            if (USLUGABIRZEWNPUBL_EXCEPTION!= null) {
                throw USLUGABIRZEWNPUBL_EXCEPTION;
            }
            return USLUGABIRZEWNPUBL_WSDL_LOCATION;
        }

    }
}
